<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <RootNamespace>DemoDataFeeder</RootNamespace>
    <AssemblyName>DemoDataFeeder</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommandLineParser" Version="2.9.1" />
    <PackageReference Include="StatsdCsharpClient" Version="1.2.1.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="App.config" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
