<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <RootNamespace>statsd.net</RootNamespace>
    <AssemblyName>statsdnet</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="log4net" Version="2.0.15" />
    <PackageReference Include="Microsoft.Practices.TransientFaultHandling.Core" Version="5.1.1209.1" />
    <PackageReference Include="System.Net.Http.Json" Version="8.0.0" />
    <PackageReference Include="StatsdCsharpClient" Version="1.2.1.0" />
    <PackageReference Include="System.Threading.Tasks.Dataflow" Version="8.0.0" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="8.0.0" />
    <PackageReference Include="System.ServiceProcess.ServiceController" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\statsd.net.core\statsd.net.core.csproj" />
    <ProjectReference Include="..\statsd.net.shared\statsd.net.shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="cors.whitelist" CopyToOutputDirectory="Always" />
    <None Update="log4net.config" CopyToOutputDirectory="Always" />
    <None Update="log4net.Debug.config" CopyToOutputDirectory="Always" />
    <None Update="log4net.Release.config" CopyToOutputDirectory="Always" />
    <None Update="statsdnet.config" CopyToOutputDirectory="Always" />
    <None Update="statsdnet.config.graphite" CopyToOutputDirectory="Always" />
    <None Update="statsdnet.config.dbrelay" CopyToOutputDirectory="Always" />
    <None Update="statsdnet.config.librato" CopyToOutputDirectory="Always" />
    <None Update="statsdnet.config.relay" CopyToOutputDirectory="Always" />
    <None Update="statsdnet.config.everything" CopyToOutputDirectory="Always" />
  </ItemGroup>
</Project>
